### ISSUE TITLE
Use GRABNEL to attack other graph-classification dataset.

### ISSUE THREAD

**Issue by Esperanto-mega** [xingchenwan/grabnel#1]
Can I use grabnel to attack other graph classification dataset, like MUTAG, without any modifications to this algorithm?

**Comment by xingchenwan** [comment]
Hi there,
you absolutely can -- the algorithm is dataset-agnostic. you'll have to:
1. train a GCN/GIN model as a victim model on the new dataset using the scripts provided in [README](https://github.com/xingchenwan/grabnel#instructions-for-use).
2. use GRABNEL to attack -- again, you should be able to just change the model path to the path to your trained model.

However, something to be noted about MUTAG is 1) it has actual node label (i.e. the atom types), so you need to preprocess the dataset properly as some other datasets do not have actual node labels and we simply use node degree as the label (as is common in GCN training) and 2) in general, you may not get chemically valid compounds after attacking MUTAG as the attacker will try to break/form new bounds depending on the attack loss only, regardless of whether the resulting compounds are still chemically valid.

Hope that helps.
